---
services:
  surfsharkvpn2:
    container_name: surfsharkvpn2
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 51421:51421
      - 51421:51421/udp
      - 8081:8081 # qbittorrent
      - 9696:9696 # prowlarr
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDR}
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:surfsharkvpn2
    container_name: qbittorrent2
    depends_on:
      - surfsharkvpn2
    environment:
      - WEBUI_PORT=8081
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/qbittorrent:/config
      - ${COMMON_PATH}:/data
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr2
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr2
    network_mode: service:surfsharkvpn2
    depends_on:
      - surfsharkvpn2
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - PROWLARR__AUTH__APIKEY=${PROWLARR_API_KEY}
    volumes:
      - ${COMMON_PATH}/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr2
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - SONARR__AUTH__APIKEY=${SONARR_API_KEY}
    volumes:
      - ${COMMON_PATH}/configs/sonarr:/config
      - ${COMMON_PATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr2
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - RADARR__AUTH__APIKEY=${RADARR_API_KEY}
    volumes:
      - ${COMMON_PATH}/configs/radarr:/config
      - ${COMMON_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=${LOCAL_UID}
  #     - PGID=${LOCAL_GID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${COMMON_PATH}/configs/bazarr:/config
  #     - ${COMMON_PATH}:/data
  #   ports:
  #     - 6767:6767

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin2
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${COMMON_PATH}/configs/jellyfin:/config
      - ${COMMON_PATH}/jellyfin/cache:/cache
      - ${COMMON_PATH}:/data
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr2
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - JELLYSEERR__AUTH__APIKEY=${JELLYSEERR_API_KEY}
    ports:
      - 5055:5055
    volumes:
      - ${COMMON_PATH}/configs/jellyseerr:/app/config
    restart: unless-stopped

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr2
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
    restart: unless-stopped

  dashdot:
    image: mauricenino/dashdot:nvidia
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    ports:
      - 3001:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      - TZ=${TZ}
      - DASHDOT_ENABLE_CPU_TEMPS="true"
      - DASHDOT_WIDGET_LIST="os,cpu,storage,ram,network,gpu"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true # Deletes old images after updating to save disk space
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Checks for updates every day at 4:00 AM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/recyclarr:/config
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - ${COMMON_PATH}/configs/tdarr/server:/app/server
      - ${COMMON_PATH}/configs/tdarr/configs:/app/configs
      - ${COMMON_PATH}/configs/tdarr/logs:/app/logs
      - ${COMMON_PATH}:/data
      - ${COMMON_PATH}/tdarr/cache:/temp
    ports:
      - 8265:8265
      - 8266:8266
    restart: unless-stopped

  tdarr_node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr_node
    environment:
      - PUID=${LOCAL_UID}
      - PGID=${LOCAL_GID}
      - TZ=${TZ}
      - nodeName=MainGPU_Node
      - serverIP=tdarr
      - serverPort=8266
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - ${COMMON_PATH}/configs/tdarr/configs:/app/configs
      - ${COMMON_PATH}/configs/tdarr/logs:/app/logs
      - ${COMMON_PATH}:/data
      - ${COMMON_PATH}/tdarr/cache:/temp
    restart: unless-stopped
